CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE PRODUCT(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION varchar(100),
    UNIT_VALUE NUMERIC(20,2)
);

CREATE TABLE REQUEST(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT(ID),
    DATE_REQUEST TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE REQUEST_ITEM(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    REQUEST_ID INTEGER REFERENCES REQUEST(ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT(ID),
    AMOUNT INTEGER
);
